/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rxtec.pitchecking.device.easen;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLong;
import com.sun.jna.Platform;
import com.sun.jna.*;
import java.util.Arrays;
import com.sun.jna.Pointer;
import java.io.FileOutputStream;
import com.rxtec.pitchecking.device.easen.Main.SDKMethod;
import com.rxtec.pitchecking.device.easen.Main.SDK_ERROR;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author demid
 */
public class ActivationDlg extends javax.swing.JDialog {
    /**
     * Creates new form ActivationDlg
     */
    private int mResult = 0;
    
    public ActivationDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                
        editLicense.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                refreshActions();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                refreshActions();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                refreshActions();
            }
        });
        
        SDKMethod sdkMethod = SDKMethod.INSTANCE;
        byte[] hwidBytes = new byte[256];
        
        try {
            sdkMethod.getCurrentHWID(hwidBytes, 256);
        } catch (Exception e) {
        }
        
        editHWID.setText(fromByteArray(hwidBytes));
        refreshActions();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        editHWID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editLicense = new javax.swing.JTextPane();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("HWID:");

        editHWID.setEditable(false);

        jLabel2.setText("License:");

        jScrollPane1.setViewportView(editLicense);

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(editHWID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 268, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(editHWID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActions() {
        try {
            btnOk.setEnabled(!editLicense.getText().isEmpty());
        } catch(Exception e) {            
        }
    }

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        try {
            String strLicense = editLicense.getText();
            
            int ret = SDKMethod.INSTANCE.setActivation(ConvertToByteArray(strLicense));
            if(ret != SDKMethod.SDK_NO_ERROR) {
                JOptionPane.showMessageDialog(null, "Activation Failed!", "Warning", JOptionPane.PLAIN_MESSAGE);
                return;
            }
            
            FileOutputStream out = new FileOutputStream("license.txt");
            out.write(editLicense.getText().getBytes());
            out.close();
            
            JOptionPane.showMessageDialog(null, "Activation Success!", "Information", JOptionPane.PLAIN_MESSAGE);
        } catch (Exception e){            
        }
        
        mResult = 1;
        dispose();        
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        mResult = 0;
        dispose();        
    }//GEN-LAST:event_btnCancelActionPerformed

    public int getResult() {
        return mResult;
    }   
    
    public static byte[] ConvertToByteArray(String str) {
        byte[] bytes = new byte[str.length() + 1];
        Arrays.fill(bytes, (byte)0);
        System.arraycopy(str.getBytes(), 0, bytes, 0, str.getBytes().length);
        
        return bytes;
    }

    public static String fromByteArray(byte[] array) {
        int realLen = 0;

        for (int i = 0; i < array.length; i++) {
            if (array[i] != 0)
                realLen++;
            else
                break;
        }

        byte[] realStr = new byte[realLen];
        System.arraycopy(array, 0, realStr, 0, realLen);

        return new String(realStr);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JTextField editHWID;
    private javax.swing.JTextPane editLicense;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
